name: CI/CD to Docker Hub

on:
  push:
    branches:
      -main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/Checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build, Tag, and Push Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_REPO: ${{ secrets.DOCKER_HUB_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker compose -f docker-compose.yml Build
          
          docker tag cicdtest:v1 $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG

          docker push $DOCKER_USER/$DOCKER_REPO:$IMAGE_TAG